# Font configuration (changes require restart)
font:
  # The size to use.
  size: 14
  # The normal (roman) font face to use.
  normal:
    family: CodeNewRoman Nerd Font Mono
    # Style can be specified to pick a specific face.
    style: Book

  # The bold font face
  bold:
    family: CodeNewRoman Nerd Font Mono
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: CodeNewRoman Nerd Font Mono
    # Style can be specified to pick a specific face.
    style: Italic

# https://github.com/eendroroy/alacritty-theme
# Colors (Ayu Dark)
colors:
  # Default colors
  primary:
    background: '0x0A0E14'
    foreground: '0xB3B1AD'

  # Normal colors
  normal:
    black:   '0x01060E'
    red:     '0xEA6C73'
    green:   '0x91B362'
    yellow:  '0xF9AF4F'
    blue:    '0x53BDFA'
    magenta: '0xFAE994'
    cyan:    '0x90E1C6'
    white:   '0xC7C7C7'

  # Bright colors
  bright:
    black:   '0x686868'
    red:     '0xF07178'
    green:   '0xC2D94C'
    yellow:  '0xFFB454'
    blue:    '0x59C2FF'
    magenta: '0xFFEE99'
    cyan:    '0x95E6CB'
    white:   '0xFFFFFF'
